services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local-spendsense
    ports:
      - "8000:8000"
    user: root
    volumes:
      - dynamodb_local_spendsense:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
volumes:
  dynamodb_local_spendsense:
