services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local-spendsense
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 256M
volumes:
  dynamodb_data:
